const path = require('path');
const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const TerserPlugin = require('terser-webpack-plugin');
const hostname = '0.0.0.0';
const port = '8080';

module.exports = function(env, argv) {
	return {
		entry: './src/index.js',
		plugins: [
			new HtmlWebpackPlugin({
				inject: true, // Inject all files that are generated by webpack, e.g. bundle.js
				template: 'index.html',
			}),
		],
		output: {
			path: path.resolve(__dirname, 'dist'),
			filename: 'slot.js',
		},
		module: {
			rules: [
				{
					test: /\.html$/,
					use: 'html-loader',
				},
				{
					test: /\.?js$/,
					exclude: /(node_modules|bower_components)/,
					use: {
						loader: 'babel-loader',
					},
				},
			],
		},
		devServer: {
			host: hostname,
			port,
			open: false,
		},
		optimization: {
			minimize: true,
			minimizer: [
				new TerserPlugin({
					terserOptions: {
						ie8: true,
						safari10: true,
						warnings: false,
						compress: {
							comparisons: true,
						},
						parse: {},
						mangle: true,
						output: {
							comments: false,
							ascii_only: true,
						},
					},
					cache: false,
					sourceMap: false,
				}),
			],
			nodeEnv: 'production',
			usedExports: true,
			sideEffects: false,
		},
		name: 'your-project',
		resolve: {
			alias: {
				react: 'preact-compat',
				'react-dom': 'preact-compat',
				// Not necessary unless you consume a module using `createClass`
				'create-react-class': 'preact-compat/lib/create-react-class',
				// Not necessary unless you consume a module requiring `react-dom-factories`
				'react-dom-factories': 'preact-compat/lib/react-dom-factories',
			},
		},
	};
};
